[package]
name = "ash-testapp"
version = "0.1.0"
edition = "2018"

[dependencies]
winit = "0.20.0"
ash = "0.29.0"
num = "0.2"
winapi = { version = "0.3.5", features = ["windef", "libloaderapi"] }
memoffset = "0.5.1"
cgmath = "0.17.0"
image = "0.22"

[dependencies.util]
path = "../util"